// ui/ratings/RatingsDummyData.kt
package com.example.week1.ui.ratings

object RatingsDummyData {
    fun getRatings(): List<RatingItem> {
        return listOf(
            RatingItem("15겹크레페", "file:///android_asset/sungsimdang/15겹크레페.png", 4.5f, 0f),
            RatingItem("62호밀브릇", "file:///android_asset/sungsimdang/62호밀브릇.png", 4.0f, 0f),
            RatingItem("과일생케익", "file:///android_asset/sungsimdang/과일생케익.png", 4.5f, 0f),
            RatingItem("과일시루", "file:///android_asset/sungsimdang/과일시루.png", 4.0f, 0f),
            RatingItem("노아레즌", "file:///android_asset/sungsimdang/노아레즌.png", 4.5f, 0f),
            RatingItem("단팥빵", "file:///android_asset/sungsimdang/단팥빵.png", 4.0f, 0f),
            RatingItem("딸기모짜르트", "file:///android_asset/sungsimdang/딸기모짜르트.png", 4.5f, 0f),
            RatingItem("레드와인", "file:///android_asset/sungsimdang/레드와인.png", 4.0f, 0f),
            RatingItem("망고시루", "file:///android_asset/sungsimdang/망고시루.png", 4.5f, 0f),
            RatingItem("맷돌로같은통밀빵", "file:///android_asset/sungsimdang/맷돌로같은통밀빵.png", 4.0f, 0f),
            RatingItem("명란바게트", "file:///android_asset/sungsimdang/명란바게트.png", 4.5f, 0f),
            RatingItem("모닝빵", "file:///android_asset/sungsimdang/모닝빵.png", 4.0f, 0f),
            RatingItem("모찌모찌식빵", "file:///android_asset/sungsimdang/모찌모찌식빵.png", 4.5f, 0f),
            RatingItem("발레리나", "file:///android_asset/sungsimdang/발레리나.png", 4.0f, 0f),
            RatingItem("보문산메아리", "file:///android_asset/sungsimdang/보문산메아리.png", 4.5f, 0f),
            RatingItem("볼케이노", "file:///android_asset/sungsimdang/볼케이노.png", 4.0f, 0f),
            RatingItem("볼콘50", "file:///android_asset/sungsimdang/볼콘50.png", 4.5f, 0f),
            RatingItem("부띠끄과일동산", "file:///android_asset/sungsimdang/부띠끄과일동산.png", 4.0f, 0f),
            RatingItem("빅매치", "file:///android_asset/sungsimdang/빅매치.png", 4.5f, 0f),
            RatingItem("빵도넛", "file:///android_asset/sungsimdang/빵도넛.png", 4.0f, 0f),
            RatingItem("뺑드깜빠뉴", "file:///android_asset/sungsimdang/뺑드깜빠뉴.png", 4.5f, 0f),
            RatingItem("소금크롸상", "file:///android_asset/sungsimdang/소금크롸상.png", 4.0f, 0f),
            RatingItem("소보로", "file:///android_asset/sungsimdang/소보로.png", 4.5f, 0f),
            RatingItem("순수롤", "file:///android_asset/sungsimdang/순수롤.png", 4.0f, 0f),
            RatingItem("순수마들렌", "file:///android_asset/sungsimdang/순수마들렌.png", 4.5f, 0f),
            RatingItem("순수생케익", "file:///android_asset/sungsimdang/순수생케익.png", 4.0f, 0f),
            RatingItem("스테이크빵", "file:///android_asset/sungsimdang/스테이크빵.png", 4.5f, 0f),
            RatingItem("에멘탈바질바게트", "file:///android_asset/sungsimdang/에멘탈바질바게트.png", 4.0f, 0f),
            RatingItem("오보름달", "file:///android_asset/sungsimdang/오보름달.png", 4.5f, 0f),
            RatingItem("오징어먹물방망이", "file:///android_asset/sungsimdang/오징어먹물방망이.png", 4.0f, 0f),
            RatingItem("요거트롤", "file:///android_asset/sungsimdang/요거트롤.png", 4.5f, 0f),
            RatingItem("윌넛브레드", "file:///android_asset/sungsimdang/윌넛브레드.png", 4.0f, 0f),
            RatingItem("작은메아리", "file:///android_asset/sungsimdang/작은메아리.png", 4.5f, 0f),
            RatingItem("찹쌀방망이", "file:///android_asset/sungsimdang/찹쌀방망이.png", 4.0f, 0f),
            RatingItem("축복", "file:///android_asset/sungsimdang/축복.png", 4.5f, 0f),
            RatingItem("크림치즈화이트번", "file:///android_asset/sungsimdang/크림치즈화이트번.png", 4.0f, 0f),
            RatingItem("키다리트위스트", "file:///android_asset/sungsimdang/키다리트위스트.png", 4.5f, 0f),
            RatingItem("토요빵", "file:///android_asset/sungsimdang/토요빵.png", 4.0f, 0f),
            RatingItem("튀소구마", "file:///android_asset/sungsimdang/튀소구마.png", 4.5f, 0f),
            RatingItem("티라미수룰", "file:///android_asset/sungsimdang/티라미수룰.png", 4.0f, 0f),
            RatingItem("파이만주세트", "file:///android_asset/sungsimdang/파이만주세트.png", 4.5f, 0f),
            RatingItem("판타롱부추빵", "file:///android_asset/sungsimdang/판타롱부추빵.png", 4.0f, 0f),
            RatingItem("팡오레", "file:///android_asset/sungsimdang/팡오레.png", 4.5f, 0f),
            RatingItem("플레인크롸상", "file:///android_asset/sungsimdang/플레인크롸상.png", 4.0f, 0f),
            RatingItem("해바라기", "file:///android_asset/sungsimdang/해바라기.png", 4.5f, 0f),
            RatingItem("호두파이", "file:///android_asset/sungsimdang/호두파이.png", 4.0f, 0f),
            RatingItem("호밀샤워브레드", "file:///android_asset/sungsimdang/호밀샤워브레드.png", 4.5f, 0f),
            RatingItem("화쏘브레드", "file:///android_asset/sungsimdang/화쏘브레드.png", 4.0f, 0f),
            RatingItem("후렌치파이", "file:///android_asset/sungsimdang/후렌치파이.png", 4.5f, 0f),
            RatingItem("후르츠브롯", "file:///android_asset/sungsimdang/후르츠브롯.png", 4.0f, 0f),
            RatingItem("S브레드", "file:///android_asset/sungsimdang/S브레드.png", 4.5f, 0f)
        )
    }
}